default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: wonderful_editor_development
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  username: <%= ENV["PGUSER"] || ENV["POSTGRES_USER"] || ENV["USER"] || "postgres" %>
  password: <%= ENV["PGPASSWORD"] || ENV["POSTGRES_PASSWORD"] || "" %>

test:
  <<: *default
  database: wonderful_editor_test
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  username: <%= ENV["PGUSER"] || ENV["POSTGRES_USER"] || ENV["USER"] || "postgres" %>
  password: <%= ENV["PGPASSWORD"] || ENV["POSTGRES_PASSWORD"] || "" %>

production:
  <<: *default
  # Render の Postgres アドオン or 外部DB を使う想定
  url: <%= ENV["DATABASE_URL"] %>
